---

services:
  app:
    build: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !override
      - artifacts:/opt/app/artifacts
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?error}

  db:
    volumes: !reset

volumes:
  artifacts:
