test:
  url: 'mysql2://root:root@db:3306/NARA_TEST'
  reconnect: true

development:
  url: 'mysql2://root:root@db:3306/NARA_DEV'
  reconnect: true

production:
  url: <%= ENV['DATABASE_URL'] %>
  reconnect: true
