test:
  url: 'mysql2://root:password1@db:3306/NARA_TEST'

development:
  url: 'mysql2://root:password1@db:3306/NARA_DEV'

production:
  adapter: mysql2
  host: db
  port: 3306
  database: NARA
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  pool: 5
  timeout: 5000
