test:
  url: 'mysql2://root:root@db:3306/NARA_TEST'
  reconnect: true

development:
  url: 'mysql2://root:root@db:3306/NARA_DEV'
  reconnect: true

production:
  adapter: mysql2
  host: db
  port: 3306
  database: NARA
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  pool: 5
  timeout: 5000
