test:
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:root@db:3306/NARA_TEST' %>
  reconnect: true

development:
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:root@db:3306/NARA_DEV' %>
  reconnect: true

production:
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:root@db:3306/NARA_PROD' %>
  reconnect: true
